### ISSUE TITLE
安装后端后运行 python server.py报错

### ISSUE THREAD

**Issue by MrPangzhan** [ssrpanel/SSRPanel#1075]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问
求助各位大佬！
[root@jp shadowsocksr]# python server.py
IPv6 support
Traceback (most recent call last):
  File "server.py", line 25, in <module>
    import db_transfer
  File "/root/shadowsocksr/db_transfer.py", line 13, in <module>
    from database import *
  File "/root/shadowsocksr/database/__init__.py", line 9, in <module>
    from peewee import *
ImportError: No module named peewee

**Comment by MrPangzhan** [comment]
已解决，未安装shadowsocksr依赖包。

**Comment by adhll** [comment]
仔细看你最后一句的提示，明显依赖没装

**Comment by aoerboquartz** [comment]
你好，我也碰到了这个问题，请问需要安装哪些依赖？
