### ISSUE TITLE
前后端同一机器的搭建报错

### ISSUE THREAD

**Issue by DizzlyLee** [ssrpanel/SSRPanel#1167]
前段已安装好，后端到运行这个python server.py错误信息如下

IPv6 support
[INFO] util.py:94(find_library) loading libcrypto from libcrypto.so.10
[INFO] asyncdns.py:287(__init__) black_hostname_list init as : []
[INFO] asyncdns.py:335(_parse_resolv) dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
[INFO] shell.py:74(log_shadowsocks_version) ShadowsocksR SSRR 3.2.2 2018-05-22
[INFO] db_transfer.py:251(thread_db) current process RLIMIT_NOFILE resource: soft 1000000 hard 1000000
[ERROR] db_transfer.py:280(thread_db) Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 261, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 377, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 598, in connect
    self._request_authentication()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
OperationalError: (1045, u"Access denied for user 'root'@'localhost' (using password: YES)")

^CTraceback (most recent call last):
  File "server.py", line 57, in main
    thread.join(10.0)
  File "/usr/lib64/python2.7/threading.py", line 962, in join
    self.__block.wait(delay, balancing)
  File "/usr/lib64/python2.7/threading.py", line 362, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by DizzlyLee** [comment]
另外在后台节点列表，右下角红色添加了节点，前端普通用户节点和VIP用户节点都是空的。

**Comment by vft9nesd** [comment]
https://github.com/shadowsocksrr/shadowsocksr/releases/tag/3.2.2 用这个后端吧  用胖虎的后端我也遇到一些问题

**Comment by MrPangzhan** [comment]
没有安装shadowsocks依赖
1、首先需要安装pip
yum -y install python-setuptools
easy_install pip
2、在安装依赖包试下
cd shadowsocksr
pip install -r requestment.txt

**Comment by ssrpanel** [comment]
OperationalError: (1045, u"Access denied for user 'root'@'localhost' (using password: YES)")

**Comment by ssrpanel** [comment]
啧啧啧

**Comment by DizzlyLee** [comment]
解决了大佬。手残点了那个重置root密码。我说咋回事。

> 啧啧啧
