### ISSUE TITLE
【异常】自动关闭超时未支付订单

### ISSUE THREAD

**Issue by GaHoKwan** [ssrpanel/SSRPanel#1312]
【异常】自动关闭超时未支付订单：ErrorException: Trying to get property of non-object 
in /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php:505

Stack trace: #0 /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php(505): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/www/wwwroot/ss...', 505, Array) #1 /www/wwwroot/ssrpanel/app/Console/Commands/AutoJob.php(76): App\Console\Commands\AutoJob->closeOrders() #2 [internal function]: App\Console\Commands\AutoJob->handle() #3 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #4 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #5 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #6 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #7 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array) #8 /www/wwwroot/ssrpanel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #9 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #10 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(901): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoJob), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /www/wwwroot/ssrpanel/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /www/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /www/wwwroot/ssrpanel/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by GaHoKwan** [comment]
还有，在线IP监控是空的，但是节点上的回报正常
