### ISSUE TITLE
配置节点 对接数据库 出现问题 却能正常使用

### ISSUE THREAD

**Issue by redtechma** [ssrpanel/SSRPanel#1376]
Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 260, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 71, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer) #返回有更新的表
  File "/root/shadowsocksr/db_transfer.py", line 492, in update_all_user
    db=self.cfg["db"], charset='utf8')
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxx.xxx.xx.x' (timed out)")
端口 防火墙 权限 放开
我配置的还是单端口  日志里各种error warning 上网却是正常的
望大佬 解答

**Comment by vft9nesd** [comment]
pip install pymysql

**Comment by redtechma** [comment]
> pip install pymysql

[ERROR] db_transfer.py:280(thread_db) Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 261, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 377, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'xxxxxxxxx' (timed out)")

我换成pthon2.7了  又变成这样了 
谢谢您的回答

**Comment by vft9nesd** [comment]
Can't connect to MySQL server on u'xxxxxxxxx' (timed out)"
![image](https://user-images.githubusercontent.com/24932999/53025095-498c0880-349b-11e9-9507-a40a6760901c.png)
