### ISSUE TITLE
手动部署后端报错

### ISSUE THREAD

**Issue by FPSRussia** [ssrpanel/SSRPanel#1451]

**Comment by FPSRussia** [comment]
[ERROR] db_transfer.py:280(thread_db) Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pymysql/connections.py", line 582, in connect
    **kwargs)
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/root/.pyenv/versions/3.7.1/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
