### ISSUE TITLE
定时任务无效问题

### ISSUE THREAD

**Issue by wangrong1994** [ssrpanel/SSRPanel#234]
我想教一下，定时任务我加在了crontab中，但不会自动执行，需要手动php /home/wwwroot/ssrpanel/artisan schedule:run这样运行一下，原因是什么呢？

**Comment by ssrpanel** [comment]
贴出来日志。日志位于storage/logs/下，

**Comment by wangrong1994** [comment]
#57 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /home/wwwroot/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /home/wwwroot/ssrpanel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}  
[2018-01-15 15:39:46] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-15 15:39:48] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-15 15:39:49] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-15 15:39:49] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-15 15:39:50] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-15 15:39:50] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-15 15:39:50] production.INFO: 定时任务：自动解封用户  
[2018-01-15 15:39:50] production.INFO: 定时任务：自动解封用户  
[2018-01-15 15:49:00] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-15 15:49:00] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-15 15:49:00] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-15 15:49:00] production.INFO: 定时任务：自动解封用户  
[2018-01-15 16:11:30] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-15 16:11:30] production.INFO: 定时任务：自动禁用到期用户  
 
最新日志是2018-01-15的，昨天有段时间我手动执行了定时任务命令

**Comment by wangrong1994** [comment]
刚才我测试用户流量到期封禁，ssr服务器已经显示：
2018-01-16 11:38:04 INFO     db_transfer.py:160 db stop server at port [10001]
2018-01-16 11:38:04 INFO     server_pool.py:184 stopped server at 0.0.0.0:10001 already stop
2018-01-16 11:38:04 INFO     server_pool.py:202 stopped server at [::]:10001
2018-01-16 11:38:06 INFO     tcprelay.py:1462 closed TCP port 10001
2018-01-16 11:38:06 INFO     tcprelay.py:1358 port 10001 connections down to 0
2018-01-16 11:38:06 INFO     tcprelay.py:1382 Total connections down to 0
2018-01-16 11:38:06 INFO     udprelay.py:638 closed UDP port 10001

但定时任务日志是没有进行跑：
[root@bogon logs]# tail -f laravel-2018-01-16.log 
[2018-01-16 11:33:17] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-16 11:33:17] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-16 11:33:18] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-16 11:33:18] production.INFO: 定时任务：自动解封用户  
[2018-01-16 11:34:27] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-16 11:34:27] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-16 11:34:27] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-16 11:34:27] production.INFO: 定时任务：自动解封用户 

管理中心的用户列表页面上用户的SSR(R)状态仍然还是启用，但此时是不可以使用VPS了，

**Comment by wangrong1994** [comment]
现在可以了，我把/etc/crontab改成
*  *  *  *  * root /usr/bin/php -q /home/wwwroot/ssrpanel/artisan schedule:run >> /dev/null 2>&1

**Comment by a327958099** [comment]
@wangrong1994   我的还是不行，还是无法自动发送邮件

**Comment by a327958099** [comment]
@ssrpanel   邮件流量自动提醒不行，无法自动发送邮件，这个功能可以通过URL的方式访问执行吗？如果可以的话怎么访问啊，感谢！

**Comment by ssrpanel** [comment]
@wangrong1994 错误日志不完整，多贴点

**Comment by wangrong1994** [comment]
@ssrpanel 现在没有问题了，谢谢你，但是邮件流量自动提醒好像没自动执行，执行了定时的任务有：
[2018-01-17 11:28:01] production.INFO: 定时任务：自动解封用户  
[2018-01-17 11:29:02] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-17 11:29:02] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-17 11:29:02] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-17 11:29:02] production.INFO: 定时任务：自动解封用户  
[2018-01-17 11:30:01] production.INFO: 定时任务：自动封禁异常订阅链接  
[2018-01-17 11:30:01] production.INFO: 定时任务：自动封禁用户  
[2018-01-17 11:30:01] production.INFO: 定时任务：自动监测节点是否宕机  
[2018-01-17 11:30:02] production.INFO: 定时任务：自动清除日志  
[2018-01-17 11:30:02] production.INFO: 定时任务：自动扣除用户到期流量包的流量  
[2018-01-17 11:30:02] production.INFO: 定时任务：自动禁用到期用户  
[2018-01-17 11:30:02] production.INFO: 定时任务：自动禁用流量超限的用户  
[2018-01-17 11:30:02] production.INFO: 定时任务：优惠券到期自动置无效  
[2018-01-17 11:30:02] production.INFO: 定时任务：邀请码过期自动置无效 
 @a327958099 我的也没执行，

**Comment by wangrong1994** [comment]
@ssrpanel 定时任务执行没有问题了，但有个问题是自动发送邮件提醒用户这个定时任务执行后(我设置了此任务为everyMinute执行)并没有发送邮件，你的也是吗? @a327958099

**Comment by wangrong1994** [comment]
@ssrpanel  
查看了emial_log数据库，最新日志是1-15号的，显示连接 smtp.qq.com error
|  5 |       2 | 重新激活账号       | 请求地址：http://www.ssrpanel3.com/active/fec4754d05cd54df3034d70787a7161b      |      0 | Connection could not be established with host smtp.qq.com [ #0]       | 2018-01-15 20:08:55 |
|  6 |       2 | 重新激活账号       | 请求地址：http://www.ssrpanel3.com/active/91272341e600355372283f46fa042210      |      1 |                                                                       | 2018-01-16 10:45:52 |
今天再观察观察吧，数据不够多

**Comment by a327958099** [comment]
可以了，我昨天设置的的，今天凌晨 00:02分的时候时候邮件统一自动发送了，而且另外一个问题，设置自动发送邮件后服务器有规律的出现高负荷状况
![qq20180118-023706](https://user-images.githubusercontent.com/26393031/35060374-44665242-fbf9-11e7-85f7-dc4d9919f80d.png)

**Comment by wangrong1994** [comment]
@a327958099 你是在后台设置的对吧，高负荷这个就不太清楚了

**Comment by q65686488** [comment]
* * * * * root /usr/local/php/bin/php -q /home/wwwroot/default/artisan schedule:run >> /dev/null 2>&1

**Comment by ssrpanel** [comment]
@wangrong1994 高负荷是正常的，短时间内的罢了，并不影响，因为数据库日志量大，别跟我说你们都是用什么512M内存来跑面板。。推荐1G KVM机。。

**Comment by ssrpanel** [comment]
@q65686488 你为什么要带上参数q？有这个参数吗？

**Comment by 828768** [comment]
检查下是不是用户目录的事，没人提及过要看cron的日志啊：[记一次系统任务无法正常执行](https://sobaigu.com/linux-schedule-donot-run-with-crond.html)
