### ISSUE TITLE
如何升级旧版到最新版？最新版安装文档是首页的readme.md吗？

### ISSUE THREAD

**Issue by wuwentao** [ssrpanel/SSRPanel#246]
之前安装的旧版，因为文档没更新，只有旧版的安装文档，所以就按旧版的文档安装在用了
那么问题是：
1.如何升级2.0版本到现在最新的呢？（如何确定自己的版本号）
2.最新版的全新安装文档是目前首页中的readme.md吗？

PS:确实如果比较麻烦，可以先介绍一下大概流程和步骤，一些重要的细节点等，我可以本地尝试一下。
谢谢！

为什么要升级：
旧版基本功能貌似ok，不过貌似有不少bug，例如上传报错，storage已经777了，发邮件报错，还有很多管理链接点击也有问题，主要需要备份的：
1.用户登陆的用户名，密码
2.用户连接的客户端配置信息，例如端口，密码，加密算法这类的配置，避免升级后还需要修改客户端配置。
除此之外还有哪些需要备份或升级？

```
 git log  |more
commit dda0dc8fecb69a394f9a76e0af584c7f2d6580d3
Author: zhangjiangbin <zhangjiangbin@zhijiesong.com>
Date:   Tue Nov 28 19:03:14 2017 +0800

    用户、节点流量监控优化

commit 9e2ad1e9cf26e804be942df90ae9cc4a75736a02
Author: zhangjiangbin <zhangjiangbin@zhijiesong.com>
Date:   Tue Nov 28 18:14:53 2017 +0800

    1.用户、节点流量监控页面美化
    2.更新readme

commit 7bf71f98624d17385f2ceb0f0438536b73484f10
Author: zhangjiangbin <zhangjiangbin@zhijiesong.com>
Date:   Tue Nov 28 09:24:18 2017 +0800

    订阅链接不应该出现维护中的节点

```

**Comment by ssrpanel** [comment]
@wuwentao 你把数据库备份好，主要是ss_node 表、user表，最好是更新到最新版本

**Comment by wuwentao** [comment]
谢谢，目前git的latest code，最新版的安装文档是首页readme.md吧？
wiki里面的不确定了

**Comment by wuwentao** [comment]
@ssrpanel 已更新最新的版本，database部分还是有不少问题，主要问题基本都是这一块，手工挨个在mysql下souce了所有的sql/update和db.sql
最后insert备份的数据库还是不少格式不兼容。
导入ss_node时也一样不行，尝试在web上添加，输入所有信息后没反应，后来手工挨个编辑sql语句，强行insert到ss_node的database里面去了！
另外web上编辑节点信息，提交也没反应，是否有bug？还是我database有问题？

在没有任何node时，手工在web后台添加，debug的log错误如下：
Column 'protocol_param' cannot be null

```
5685 #67 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline-                   >Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
5686 #68 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline-             >then(Object(Closure))
5687 #69 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel-        >sendRequestThroughRouter(Object(Illuminate\Http\Request))
5688 #70 /srv/www/git/ssrpanel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
5689 #71 {main}
5690
5691 Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'protocol_param' cannot be null        (SQL: insert into `ss_node` (`name`, `group_id`, `country_code`, `server`, `desc`, `method`, `custom_method`, `protocol`,                    `protocol_param`, `obfs`, `obfs_param`, `traffic_rate`, `bandwidth`, `traffic`, `monitor_url`, `compatible`, `single`, `single_force`,       `single_port`, `single_passwd`, `single_method`, `single_protocol`, `single_obfs`, `sort`, `status`, `updated_at`, `created_at`) values      (test, 3, jp, s1.vpn.cn, s1.vpn.cn, chacha20, chacha20, auth_aes128_sha1, , tls1.2_ticket_auth, , 1.0, 1000, 1000, https://www.vpn.cn/, 0, 0, 0, , , , , , 1, 1, 2018-01-25 11:41:41, 2018-01-25 11:41:41)) in /srv/www/git/ssrpanel/vendor/laravel/framework/src/        Illuminate/Database/Connection.php:647
5692 Stack trace:
5693 #0 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection-               >runQueryCallback('insert into `ss...', Array, Object(Closure))
5694 #1 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection-               >run('insert into `ss...', Array, Object(Closure))
```
