### ISSUE TITLE
安装最新版，按照首页readme.md执行，发现的问题

### ISSUE THREAD

**Issue by wuwentao** [ssrpanel/SSRPanel#247]
@ssrpanel 已更新最新的版本，database部分还是有不少问题，主要问题基本都是这一块，手工挨个在mysql下souce了所有的sql/update和db.sql
最后insert备份的数据库还是不少格式不兼容。

问题1： 可否在sql目录下增加一个最新的完整版sql文件？而旧版的保留即可，通过update下逐个升级。

问题2： insert导入备份的ss_node表或者手工在web后台上添加，输入所有表单信息后没反应（分组已导入了database），后来手工挨个编辑sql语句，强行insert数据到ss_node的database里面去了！
insert进去以后，直接在web上编辑节点信息，提交也没反应，是否有bug？还是我database有问题？

问题3： 编辑ss_node的protocol信息，database中设置的是auth_aes128_sha，查看时没问题，但是点编辑，进入编辑form里会显示为origin，而不是database中的值。

在没有任何ss_node信息时，手工在web后台添加，debug的log错误如下：
Column 'protocol_param' cannot be null

```
5685 #67 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline-                   >Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
5686 #68 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline-             >then(Object(Closure))
5687 #69 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel-        >sendRequestThroughRouter(Object(Illuminate\Http\Request))
5688 #70 /srv/www/git/ssrpanel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
5689 #71 {main}
5690
5691 Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'protocol_param' cannot be null        (SQL: insert into `ss_node` (`name`, `group_id`, `country_code`, `server`, `desc`, `method`, `custom_method`, `protocol`,                    `protocol_param`, `obfs`, `obfs_param`, `traffic_rate`, `bandwidth`, `traffic`, `monitor_url`, `compatible`, `single`, `single_force`,       `single_port`, `single_passwd`, `single_method`, `single_protocol`, `single_obfs`, `sort`, `status`, `updated_at`, `created_at`) values      (test, 3, jp, s1.vpn.cn, s1.vpn.cn, chacha20, chacha20, auth_aes128_sha1, , tls1.2_ticket_auth, , 1.0, 1000, 1000, https://www.vpn.cn/, 0, 0, 0, , , , , , 1, 1, 2018-01-25 11:41:41, 2018-01-25 11:41:41)) in /srv/www/git/ssrpanel/vendor/laravel/framework/src/        Illuminate/Database/Connection.php:647
5692 Stack trace:
5693 #0 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection-               >runQueryCallback('insert into `ss...', Array, Object(Closure))
5694 #1 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection-               >run('insert into `ss...', Array, Object(Closure))
```

git的代码已经同步最新的master：
```
root@vpn:/srv/www/git/ssrpanel# git branch
* master
root@vpn:/srv/www/git/ssrpanel# git pull
Already up-to-date.
root@vpn:/srv/www/git/ssrpanel# git tag
1.0
V2.0
V3.0
V3.1
V3.2
root@vpn:/srv/www/git/ssrpanel#
```

问题4： 用户订阅时报错：
```
SQLSTATE[HY000]: General error: 1364 Field 'ban_desc' doesn't have a default value (SQL: insert into `user_subscribe` (`user_id`, `code`, `times`, `updated_at`, `created_at`) values (1, b96c800f6252, 0, 2018-01-25 12:57:15, 2018-01-25 12:57:15))
```

问题5：用户注册报错：
```
Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1364 Field 'remark' doesn't have a default value (SQL: insert into `user` (`username`,                 `password`, `port`, `passwd`, `transfer_enable`, `method`, `protocol`, `obfs`, `enable_time`, `expire_time`, `reg_ip`, `referral_uid`, `updated_at`, `created_at`) values       (xxx@qq.com, ae3e8198c92b1e744687e8b1ae8f5dac, 10006, 2AvQ38, 2147483648, chacha20, auth_aes128_sha1, tls1.2_ticket_auth, 2018-01-31 16:38:07, 2018-02-07 16:38:07,        11.23.25.3, 1, 2018-01-31 16:38:07, 2018-01-31 16:38:07)) in /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
5698 Stack trace:
5699 #0 /srv/www/git/ssrpanel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `us...',           Array, Object(Closure))
```

**Comment by ssrpanel** [comment]
估计是播种机有问题，你直接把整个数据库删除吧，导入sql/db.sql到数据库，这个是整个库
