### ISSUE TITLE
无法订阅

### ISSUE THREAD

**Issue by kuangshao11** [ssrpanel/SSRPanel#400]
今天重新安装的，导入的是3月10几号的数据库，现在标签管理和订单管理点进去就是404，并且无法订阅，订阅地址是以前用的，重装后不可用了。

**Comment by kuangshao11** [comment]
这是手机ssrr订阅错误时的日志

04-07 19:46:13.023 21308 21308 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
04-07 19:46:14.043 21308 21383 D OpenGLRenderer: endAllActiveAnimators on 0xd55a4980 (RippleDrawable) with handle 0xeb603860
04-07 19:46:34.684 21308 21349 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
04-07 19:46:38.521 21308 21383 D OpenGLRenderer: endAllActiveAnimators on 0xd694bb00 (RippleDrawable) with handle 0xd5395840
04-07 19:46:40.968 21308 21751 W System.err: java.lang.Exception: 地址不正确或网络不可用。
04-07 19:46:40.968 21308 21751 W System.err: 	at com.github.shadowsocks.ProfileManagerActivity$$anonfun$com$github$shadowsocks$ProfileManagerActivity$$onClick$body$13$1$$anonfun$apply$mcV$sp$2.apply(ProfileManagerActivity.scala:775)
04-07 19:46:40.968 21308 21751 W System.err: 	at com.github.shadowsocks.ProfileManagerActivity$$anonfun$com$github$shadowsocks$ProfileManagerActivity$$onClick$body$13$1$$anonfun$apply$mcV$sp$2.apply(ProfileManagerActivity.scala:729)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.collection.immutable.List.foreach(List.scala:381)
04-07 19:46:40.968 21308 21751 W System.err: 	at com.github.shadowsocks.ProfileManagerActivity$$anonfun$com$github$shadowsocks$ProfileManagerActivity$$onClick$body$13$1.apply$mcV$sp(ProfileManagerActivity.scala:729)
04-07 19:46:40.968 21308 21751 W System.err: 	at com.github.shadowsocks.ProfileManagerActivity$$anonfun$com$github$shadowsocks$ProfileManagerActivity$$onClick$body$13$1.apply(ProfileManagerActivity.scala:723)
04-07 19:46:40.968 21308 21751 W System.err: 	at com.github.shadowsocks.ProfileManagerActivity$$anonfun$com$github$shadowsocks$ProfileManagerActivity$$onClick$body$13$1.apply(ProfileManagerActivity.scala:723)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
04-07 19:46:40.968 21308 21751 W System.err: 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
04-07 19:46:54.882 21308 21308 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
04-07 19:46:55.460 21308 21349 E GoogleTagManager: Invalid macro: _gtm.loadEventEnabled
