### ISSUE TITLE
配置SSR后端出错

### ISSUE THREAD

**Issue by Dennishaha** [ssrpanel/SSRPanel#547]
翻过一遍CLOSED的Issues，和翻了一边Wiki，然后来提问~

各位大佬 我的后端出问题了。。。换了好几个vps都这样呢

用的是 cent os 7.4 64bit

[root@test shadowsocksr]# python server.py
IPv6 support
2018-05-11 22:43:25 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2018-05-11 22:43:25 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2018-05-11 22:43:25 INFO     shell.py:72 ShadowsocksR 3.4.0 2017-07-27
2018-05-11 22:43:25 INFO     db_transfer.py:238 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2018-05-11 22:43:25 ERROR    db_transfer.py:266 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 248, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 383, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/root/shadowsocksr/cymysql/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/shadowsocksr/cymysql/connections.py", line 245, in __init__
    self._connect()
  File "/root/shadowsocksr/cymysql/connections.py", line 413, in _connect
    self._request_authentication()
  File "/root/shadowsocksr/cymysql/connections.py", line 497, in _request_authentication
    auth_packet = self.read_packet()
  File "/root/shadowsocksr/cymysql/connections.py", line 418, in read_packet
    return MysqlPacket(self)
  File "/root/shadowsocksr/cymysql/packet.py", line 65, in __init__
    raise_mysql_exception(self.__data)
  File "/root/shadowsocksr/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/root/shadowsocksr/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1043, u'Bad handshake')

命令用了这些呢，，，，😂
:: 宝塔安装
yum install -y wget && wget -O install.sh http://download.bt.cn/install/install.sh && sh install.sh
:: 安装 SSR
cd /root
git clone -b manyuser https://github.com/shadowsocksrr/shadowsocksr.git
cd shadowsocksr
./setup_cymysql.sh
./initcfg.sh
nano userapiconfig.py
nano user-config.json
nano usermysql.json
python server.py
./run.sh

小的看不是很懂

**Comment by biigaa** [comment]
把shadowsocksr目录下的cymysql目录删除!
去https://github.com/nakagami/CyMySQL/releases,下载0.9.5版本
解压后,重新上传到shadowsocksr目录下!!然后重启!!
问题就解决了!

**Comment by Dennishaha** [comment]
哇，好神奇，修复了，大佬这是什么原理呢（黑人问号）？？？

**Comment by biigaa** [comment]
@Dennishaha 解决就好!!Cymysql版本太新!不兼容!

**Comment by Dennishaha** [comment]
@biigaa 谢谢大佬
