### ISSUE TITLE
在最新master版本中进行安装。连接首页是报500 internal 错误。看laravel***.log有下面的错误.

### ISSUE THREAD

**Issue by JMVoid** [ssrpanel/SSRPanel#877]
[2018-08-31 19:51:07] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Maatwebsite\Excel\ExcelServiceProvider' not found in /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
Stack trace:
#0 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('Maatwebsite\\Exc...')
#1 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /home/wwwroot/default/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}  
[2018-08-31 20:17:34] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Maatwebsite\Excel\ExcelServiceProvider' not found in /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
Stack trace:
#0 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('Maatwebsite\\Exc...')
#1 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /home/wwwroot/default/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}  
[2018-08-31 20:21:18] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Maatwebsite\Excel\ExcelServiceProvider' not found in /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
Stack trace:
#0 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('Maatwebsite\\Exc...')
#1 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /home/wwwroot/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /home/wwwroot/default/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}

**Comment by JMVoid** [comment]
执行
$ php artisan
也有报下面的错:
In ProviderRepository.php line 208:
                                                            
  Class 'Maatwebsite\Excel\ExcelServiceProvider' not found

**Comment by JMVoid** [comment]
已修正。 需要将./config/app.php 中
  Maatwebsite\Excel\ExcelServiceProvider::class,
和
'Excel' => Maatwebsite\Excel\Facades\Excel::class,
comment掉后就能正常启动，访问首页

**Comment by JMVoid** [comment]
已修正。 需要将./config/app.php 中
Maatwebsite\Excel\ExcelServiceProvider::class,
和
'Excel' => Maatwebsite\Excel\Facades\Excel::class,
comment掉后就能正常启动，访问首页
关掉该issue
