### ISSUE TITLE
有一个奇怪的警告·

### ISSUE THREAD

**Issue by cmmdwl** [ssrpanel/SSRPanel#917]
ErrorException: Undefined property: stdClass::$alive 
in /www/wwwroot/be*r.com/app/Console/Commands/AutoCheckNodeStatus.php:101
Stack trace:
#0 /www/wwwroot/be*r.com/app/Console/Commands/AutoCheckNodeStatus.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/www/wwwroot/be...', 101, Array)
#1 /www/wwwroot/be*r.com/app/Console/Commands/AutoCheckNodeStatus.php(50): App\Console\Commands\AutoCheckNodeStatus->tcpCheck('172.96.218.13')
#2 /www/wwwroot/be*r.com/app/Console/Commands/AutoCheckNodeStatus.php(34): App\Console\Commands\AutoCheckNodeStatus->checkNodes()
#3 [internal function]: App\Console\Commands\AutoCheckNodeStatus->handle()
#4 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#9 /www/wwwroot/be*r.com/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /www/wwwroot/be*r.com/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/wwwroot/be*r.com/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoCheckNodeStatus), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/wwwroot/be*r.com/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/wwwroot/be*r.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/wwwroot/be*r.com/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}

**Comment by cmmdwl** [comment]
2018-09-15 10:00:08 提示产生时间 
是整点的
每个小时都有这样的提示

**Comment by cmmdwl** [comment]
更新后解决
