### ISSUE TITLE
请教大佬：FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/www/wwwroot/SSRPanel-

### ISSUE THREAD

**Issue by dongfangweiyu** [ssrpanel/SSRPanel#967]
请先翻一遍CLOSED的Issues，再翻一边Wiki，然后再来提问

2018/10/01 22:04:21 [error] 9955#0: *598 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/www/wwwroot/SSRPanel-4.3/storage/logs/laravel-2018-10-01.log" could not be opened: failed to open stream: Permission denied in /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array)
#1 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Logger.php(546): Monolog\Logger->addRecord(200, '\xE8\xAF\xB7\xE6\xB1\x82\xE5\xAF\xBC\xE8\x87\xB4\xE5\xBC\x82...', Array)
#4 /www/wwwroot/SSRPanel-4.3/vendor/laravel/framework/src/Illuminate/Log/Wr...
PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/www/wwwroot/SSRPanel-4.3/storage/logs/laravel-2018-10-01.log" could not be opened: failed to open stream: Permission denied in /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array)
#1 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /www/wwwroot/SSRPanel-4.3/vendor/monolog/monolog/src/Monolog/Logger.php(546): Monolog\Logger->addRecord(200, '\xE8\xAF\xB7\xE6\xB1\x82\xE5\xAF\xBC\xE8\x87\xB4\xE5\xBC\x82...', Array)
#4 /www/wwwr

这个错误是什么，从安装以来自己解决了好多个错误了，这个错误真不知道是为什么了？请教大家帮小弟看看。

**Comment by dongfangweiyu** [comment]
这个错误的提示好像是说权限的问题，我把storage目录权限已经改成777了还是有这个错误、

**Comment by JadeVane** [comment]
试试`chown www:www /www/wwwroot/SSRPanel-4.3/ -R`

**Comment by dongfangweiyu** [comment]
![image](https://user-images.githubusercontent.com/43637779/46331237-799c5180-c649-11e8-884b-6a65cb2f8d64.png)
@JadeVane  执行之后提示这个

**Comment by JadeVane** [comment]
@dongfangweiyu `chattr -i /www/wwwroot/SSRPanel-4.3/.user.ini`

**Comment by JadeVane** [comment]
然后再试一遍`chown www:www /www/wwwroot/SSRPanel-4.3/ -R`

**Comment by dongfangweiyu** [comment]
@JadeVane 操作成功了，过几个小时我再看看日志里面还有没有这个错误

**Comment by dongfangweiyu** [comment]
![image](https://user-images.githubusercontent.com/43637779/46395708-d23e1e00-c71f-11e8-8560-fcc16f695110.png)
@JadeVane 大佬，今天10-03号还是一直有这个错误。

**Comment by Hamishcn** [comment]
cat /etc/nginx/nginx.conf 看看user后面是不是www 不是就把上面的www改成user后的那个
